# Generated by Django 2.2.7 on 2019-11-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heir', '0002_heir_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othersproperty',
            name='heir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='heir.Heir'),
        ),
        migrations.AddField(
            model_name='othersproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimproperty',
            name='heir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='heir.Heir'),
        ),
        migrations.AddField(
            model_name='claimproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
