# Generated by Django 2.2.7 on 2019-11-10 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heir', '0003_auto_20191109_1308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_app', '0002_auto_20191109_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimProperty',
            new_name='CreditProperty',
        ),
    ]
