# Generated by Django 2.2.7 on 2019-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heir', '0002_heir_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heir',
            name='birthday',
            field=models.DateField(),
        ),
    ]
